version: '3.3'
services: 
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=devtest
      - MYSQL_DATABASE=ipssi
      - MYSQL_USER=demba
      - MYSQL_PASSWORD=password
    #volumes:
    #  - ./sql/demba.sql:/docker-entry-init.d
  

  nginx:
      image: nginx:latest
      ports: 
        - 4000:80
      volumes:
        - ./src/:/var/www/code
        - ./config:/etc/nginx/conf.d
      depends_on:
        - php

  php:
      build: ./images/
      volumes:
        - ./src:/var/www/code
      depends_on:
        - db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - 5000:80
  
   